### ISSUE TITLE
Error, help pls!

### ISSUE THREAD

**Issue by yemrees** [iamunixtz/LazyXss#1]
Hi, I am getting an error like this.

Do you want to test a single URL or a file of URLs? (single/file): single
Enter the single URL to test: https://jjjjjjjjjjjjjjjjjjjjjj.com/blog?s=test123
Enter the file path for payloads (default: payloads.txt): 
Enter the number of times to encode the payloads (or press Enter to skip encoding): 
Do you want to use a proxy? (y/n): n
Enter delay between requests in seconds (0 for no delay): 

2024-09-10 14:11:50,164 - INFO - [info] Loaded 1 URLs and 528 payloads.
2024-09-10 14:11:50,164 - INFO - [info] Server started on port 46969.
2024-09-10 14:11:50,164 - INFO - [info] Testing URL: https://jjjjjjjjjjjjjjjjjjjjjj.com/blog?s=test123
2024-09-10 14:11:50,167 - INFO - [info] Server started on port 46969.
2024-09-10 14:11:51,008 - WARNING - The chromedriver version (128.0.6613.119) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (120.0.6099.224); currently, chromedriver 120.0.6099.109 is recommended for chrome 120.*, so it is advised to delete the driver in PATH and retry
Traceback (most recent call last):
  File "/root/Desktop/Tools/LazyXss/lazyxss.py", line 189, in <module>
    main()
  File "/root/Desktop/Tools/LazyXss/lazyxss.py", line 180, in main
    test_xss(urls, payloads, proxies, encode_times, delay)
  File "/root/Desktop/Tools/LazyXss/lazyxss.py", line 113, in test_xss
    is_vuln, alert_text = check_xss_with_selenium(url, f"?search={test_payload}")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Desktop/Tools/LazyXss/lazyxss.py", line 82, in check_xss_with_selenium
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/root/Desktop/Tools/LazyXss/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55e1b0fda86a <unknown>
#1 0x55e1b0ca8e50 <unknown>
#2 0x55e1b0ce0e05 <unknown>
#3 0x55e1b0cdcc78 <unknown>
#4 0x55e1b0d2964e <unknown>
#5 0x55e1b0d28e66 <unknown>
#6 0x55e1b0d1d233 <unknown>
#7 0x55e1b0ceb093 <unknown>
#8 0x55e1b0cec09e <unknown>
#9 0x55e1b0fa1acb <unknown>
#10 0x55e1b0fa5a81 <unknown>
#11 0x55e1b0f8d695 <unknown>
#12 0x55e1b0fa65f2 <unknown>
#13 0x55e1b0f7286f <unknown>
#14 0x55e1b0fc9668 <unknown>
#15 0x55e1b0fc9832 <unknown>
#16 0x55e1b0fd965c <unknown>
#17 0x7f95f84bcdbb <unknown>

**Comment by iamunixtz** [comment]
Hi the problem u facing is ur using 2 differnt version of chrome drive and google chrome ```chromedriver version (128.0.6613.119) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (120.0.6099.224);``` 

All must be same version .Thanks You

**Comment by yemrees** [comment]
ok,thanks. If there was a problem, I saw it. :)
